### ISSUE TITLE
Intercepting Helipad on Official Map (Build 2189)

### ISSUE THREAD

**Issue by Rosw3lluk** [SunLi88/Cayo-shop-map#1]
As you can see the entire shop needs to move slightly to the left

https://gyazo.com/1e87854e2b72f06116057551ff513867
https://gyazo.com/678a7173ac3dd226ec23d632aca1c811
https://gyazo.com/482369e9fb1586f4d7cad336bd6f0401

Regards

**Comment by awesomegameruk** [comment]
Disregard forgot to disable a different ymap

**Comment by Rosw3lluk** [comment]
Disregard forgot to disable a different ymap.
